### ISSUE TITLE
How to call the system settings api in UserService？

### ISSUE THREAD

**Issue by Humenger** [RikkaApps/Shizuku-API#12]
```java
Settings.Secure.putString(resolver,
                Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES,
                String.format("%s/%s",packageName,serviceName));
        Settings.Secure.putInt(resolver,
                Settings.Secure.ACCESSIBILITY_ENABLED, 1);
```
The "resolver" object here cannot be obtained from UserService.

**Comment by RikkaW** [comment]
Normal content provider APIs (as well as  registerbroadcast receiver, they are documented some where) are not unavailable under UserService since its process is not a valid Android application process.

You can use `getContentProviderExternal` from `IActivityManager`. Shizuku uses content provider to send binder to user app, it also uses `getContentProviderExternal`. See https://github.com/RikkaApps/Shizuku/blob/8df3c308ecad9eed7b9b35c9b430143460ff5af9/server/src/main/java/rikka/shizuku/server/ShizukuService.java#L468.

About how to use settings provider, cs.android.com is your friend.
